package h.a.a.a;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.namespace.QName;

/* JADX INFO: compiled from: Metadata.java */
/* JADX INFO: loaded from: classes3.dex */
public class n implements Serializable {
    public static final String DEFAULT_LANGUAGE = "en";
    private static final long serialVersionUID = -2437262888962149444L;
    private boolean autoGeneratedId;
    private List<b> authors = new ArrayList();
    private List<b> contributors = new ArrayList();
    private List<c> dates = new ArrayList();
    private String language = DEFAULT_LANGUAGE;
    private Map<QName, String> otherProperties = new HashMap();
    private List<String> rights = new ArrayList();
    private List<String> titles = new ArrayList();
    private List<i> identifiers = new ArrayList();
    private List<String> subjects = new ArrayList();
    private String format = m.f6305b.getName();
    private List<String> types = new ArrayList();
    private List<String> descriptions = new ArrayList();
    private List<String> publishers = new ArrayList();
    private Map<String, String> metaAttributes = new HashMap();

    public n() {
        this.identifiers.add(new i());
        this.autoGeneratedId = true;
    }

    public b addAuthor(b bVar) {
        this.authors.add(bVar);
        return bVar;
    }

    public b addContributor(b bVar) {
        this.contributors.add(bVar);
        return bVar;
    }

    public c addDate(c cVar) {
        this.dates.add(cVar);
        return cVar;
    }

    public String addDescription(String str) {
        this.descriptions.add(str);
        return str;
    }

    public i addIdentifier(i iVar) {
        if (!this.autoGeneratedId || this.identifiers.isEmpty()) {
            this.identifiers.add(iVar);
        } else {
            this.identifiers.set(0, iVar);
        }
        this.autoGeneratedId = false;
        return iVar;
    }

    public String addPublisher(String str) {
        this.publishers.add(str);
        return str;
    }

    public String addTitle(String str) {
        this.titles.add(str);
        return str;
    }

    public String addType(String str) {
        this.types.add(str);
        return str;
    }

    public List<b> getAuthors() {
        return this.authors;
    }

    public List<b> getContributors() {
        return this.contributors;
    }

    public List<c> getDates() {
        return this.dates;
    }

    public List<String> getDescriptions() {
        return this.descriptions;
    }

    public String getFirstTitle() {
        List<String> list = this.titles;
        if (list != null && !list.isEmpty()) {
            for (String str : this.titles) {
                if (c.b.a.m.f.D3(str)) {
                    return str;
                }
            }
        }
        return "";
    }

    public String getFormat() {
        return this.format;
    }

    public List<i> getIdentifiers() {
        return this.identifiers;
    }

    public String getLanguage() {
        return this.language;
    }

    public String getMetaAttribute(String str) {
        return this.metaAttributes.get(str);
    }

    public Map<QName, String> getOtherProperties() {
        return this.otherProperties;
    }

    public List<String> getPublishers() {
        return this.publishers;
    }

    public List<String> getRights() {
        return this.rights;
    }

    public List<String> getSubjects() {
        return this.subjects;
    }

    public List<String> getTitles() {
        return this.titles;
    }

    public List<String> getTypes() {
        return this.types;
    }

    public boolean isAutoGeneratedId() {
        return this.autoGeneratedId;
    }

    public void setAuthors(List<b> list) {
        this.authors = list;
    }

    public void setContributors(List<b> list) {
        this.contributors = list;
    }

    public void setDates(List<c> list) {
        this.dates = list;
    }

    public void setDescriptions(List<String> list) {
        this.descriptions = list;
    }

    public void setFormat(String str) {
        this.format = str;
    }

    public void setIdentifiers(List<i> list) {
        this.identifiers = list;
        this.autoGeneratedId = false;
    }

    public void setLanguage(String str) {
        this.language = str;
    }

    public void setMetaAttributes(Map<String, String> map) {
        this.metaAttributes = map;
    }

    public void setOtherProperties(Map<QName, String> map) {
        this.otherProperties = map;
    }

    public void setPublishers(List<String> list) {
        this.publishers = list;
    }

    public void setRights(List<String> list) {
        this.rights = list;
    }

    public void setSubjects(List<String> list) {
        this.subjects = list;
    }

    public void setTitles(List<String> list) {
        this.titles = list;
    }

    public void setTypes(List<String> list) {
        this.types = list;
    }
}
